/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patients */
        get: operations["get_patients_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient */
        get: operations["get_patient_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Statistics */
        get: operations["get_statistics_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgeBand
         * @enum {string}
         */
        AgeBand: "0-17" | "18-39" | "40-64" | "65+";
        /** AgeBandStats */
        AgeBandStats: {
            /** @description Statistics for systolic blood pressure */
            blood_pressure_systolic?: components["schemas"]["Stats"] | null;
            /** @description Statistics for heart rate */
            heart_rate?: components["schemas"]["Stats"] | null;
            /** @description Statistics for fasting glucose */
            glucose_fasting?: components["schemas"]["Stats"] | null;
        };
        /**
         * BPStage
         * @enum {string}
         */
        BPStage: "Normal" | "Elevated" | "Stage 1" | "Stage 2" | "Hypertensive Crisis";
        /** DatasetStatistics */
        DatasetStatistics: {
            /**
             * Total Patients
             * @description Total number of patients
             */
            total_patients: number;
            /**
             * Age Bands
             * @description Statistics grouped by age band
             */
            age_bands: {
                [key: string]: components["schemas"]["AgeBandStats"] | null;
            };
        };
        /** EnrichedPatient */
        EnrichedPatient: {
            /**
             * Patient Id
             * @description Unique patient identifier
             */
            patient_id: string;
            /**
             * Age
             * @description Age of the patient in years
             */
            age: number;
            /** @description Gender (Male/Female) */
            gender: components["schemas"]["Gender"];
            /**
             * Blood Pressure Systolic
             * @description Systolic BP (mmHg)
             */
            blood_pressure_systolic: number;
            /**
             * Blood Pressure Diastolic
             * @description Diastolic BP (mmHg)
             */
            blood_pressure_diastolic: number;
            /**
             * Heart Rate
             * @description Heart rate (bpm)
             */
            heart_rate: number;
            /**
             * Respiratory Rate
             * @description Respiratory rate (breaths per minute).
             */
            respiratory_rate: number;
            /**
             * Body Temperature
             * @description Body temperature (deg. F)
             */
            body_temperature: number;
            /**
             * Oxygen Saturation
             * @description Oxygen saturation (%)
             */
            oxygen_saturation: number;
            /**
             * Glucose Fasting
             * @description Fasting blood glucose (mg/dL)
             */
            glucose_fasting: number;
            /**
             * Cholesterol Total
             * @description Total cholesterol (mg/dL)
             */
            cholesterol_total: number;
            /**
             * Pain Score
             * @description Pain score (0 to 10)
             */
            pain_score: number;
            /**
             * Diabetes
             * @description Whether patient has diabetes
             */
            diabetes: boolean;
            /**
             * Smoker
             * @description Whether patient is a smoker
             */
            smoker: boolean;
            /**
             * Pulse Pressure
             * @description Pulse pressure (systolic - diastolic)
             */
            pulse_pressure: number;
            /**
             * Mean Arterial Pressure
             * @description Mean arterial pressure (mmHg)
             */
            mean_arterial_pressure: number;
            /** @description Blood pressure stage classification */
            bp_stage: components["schemas"]["BPStage"];
            /**
             * Flags
             * @description Clinical flags
             */
            flags?: string[];
            /**
             * Risk Score
             * @description Calculated risk score
             */
            risk_score: number;
            /** @description Risk level (low/medium/high) */
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Reasons
             * @description Trace log of rules that fired
             */
            reasons?: string[];
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "Male" | "Female";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /** Stats */
        Stats: {
            /**
             * Mean
             * @description Mean value
             */
            mean: number;
            /**
             * Median
             * @description Median value
             */
            median: number;
            /**
             * Std Dev
             * @description Population standard deviation
             */
            std_dev: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_patients_patients_get: {
        parameters: {
            query?: {
                /** @description Filter by risk level */
                risk_level?: components["schemas"]["RiskLevel"] | null;
                /** @description Filter by BP stage */
                bp_stage?: components["schemas"]["BPStage"] | null;
                /** @description Filter by age band */
                age_band?: components["schemas"]["AgeBand"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichedPatient"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichedPatient"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statistics_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetStatistics"];
                };
            };
        };
    };
}
